# Icons of animals for displaying stats on a screen after each iteration
icons:
  Wolf: "ğŸº"
  Python: "ğŸ"
  Fox: "ğŸ¦Š"
  Bear: "ğŸ»"
  Eagle: "ğŸ¦…"
  Horse: "ğŸ"
  Deer: "ğŸ¦Œ"
  Rabbit: "ğŸ‡"
  Mouse: "ğŸ"
  Goat: "ğŸ¦Œ"
  Sheep: "ğŸ‘"
  Boar: "ğŸ—"
  Buffalo: "ğŸƒ"
  Duck: "ğŸ¦†"
  Caterpillar: "ğŸ›"
  Plant: "â˜˜"